<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2010-05-04 15:36

$extensionPath = t3lib_extMgm::extPath('mantis_connect');
return array(
	'tx_mantisconnect_connector' => $extensionPath . 'connectors/interface.tx_mantisconnect_connector.php',
	'tx_mantisconnect_flexform' => $extensionPath . 'pi1/class.tx_mantisconnect_flexform.php',
	'tx_mantisconnect_mantis' => $extensionPath . 'lib/class.tx_mantisconnect_mantis.php',
	'tx_mantisconnect_powermail' => $extensionPath . 'connectors/class.tx_mantisconnect_powermail.php',
	'user_mantisconnect_powermail' => $extensionPath . 'lib/user_mantisconnect_powermail.php',
);
?>